name: ${project.name}
version: ${project.version}
main: ${main.class}
authors: [SupaHam]
softdepend: [WorldEdit, WorldGuard]
commands:
  npcs:
    description: "Reloads the NPCs configuration."
    permission: "npcs.cmd.reload"
    usage: "/npcs"
